In [1]:
from scipy.stats import randint, uniform

In [2]:
ri = randint(0, 10)# 0~ 9 무작위 수 
ri.rvs(10)# 0~9 숫자 중 무작위 수를 10개 생성 

array([9, 1, 9, 0, 0, 8, 9, 0, 8, 6])

In [ ]:
import numpy as np
np.unique(ri.rvs(1000), return_counts=True) # 증복된 총 갯수를 함께 반환 

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 80,  88,  77,  98, 121, 124, 107, 125,  88,  92]))

In [6]:
ui  = uniform(0, 1) # 0~1 사이의 무작위 실수 
ui.rvs(5)# 0~1 사이에 무작위 실수를 5개 생성

array([0.65897466, 0.63376276, 0.17495695, 0.13339134, 0.71932705])