In [1]:
# numpy 배열 브로드 캐스팅 기능
import numpy as np

In [7]:
nums = np.array([1,2,3,4,5,6,7,8,9,10])
nums = np.arange(1, 11)
"""
  np.arange(10) : 0~9
    np.arange(1, 11) : 1~11
    np.arange(1, 11, 2): 1,3,5,7,9
"""
#nums = nums +10
nums = nums * 2

nums

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
# 배열 차원 변경 reshape
nums2 = nums.reshape(2, 5) # 2행 5열 
nums2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [12]:
nums3 = nums.reshape(5,2)
nums3

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [13]:
nums4 = nums.reshape(3, 1)
nums4

ValueError: cannot reshape array of size 10 into shape (3,1)

In [15]:
#nums5 = nums.reshape(10, 1)
nums5 = nums.reshape(-1, 1)# 전체 열을 전체 행의 갯수 
nums5

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18],
       [20]])

In [16]:
np.random.shuffle(nums)

In [17]:
nums

array([ 8, 16, 20, 18, 10, 14,  4, 12,  2,  6])

In [18]:
fruits = np.array(['사과', '오렌지', '바나나', '망고', '멜론'])

In [ ]:
fruits[[1,2,3]]

array(['사과', '오렌지', '바나나', '망고'], dtype='<U3')

In [23]:
fruits[[False , True, False , True, False]] #  블리언 인덱싱 

array(['오렌지', '망고'], dtype='<U3')

In [ ]:
mean = np.mean(train_input, axis=0) # 행별(특성별) 평균
std = np.std(train_inputm axis=0) # 행별 (특성별)표준 편차 

NameError: name 'train_input' is not defined

In [33]:
train_scaled = (train_input - mean) / std # 표준 점수 
train_scaled

NameError: name 'train_input' is not defined

In [31]:
from sklearn.neighbors import KNeighborsClassifier
kn =  KNeighborsClassifier()

In [32]:
kn.fit(train_scaled, train_target)

NameError: name 'train_scaled' is not defined

In [34]:
fish = np.array([[25, 150]])
fish_scaled = (fish- mean) /std
fish_scaled

NameError: name 'mean' is not defined

In [35]:
kn.predict(fish_scaled)

NameError: name 'fish_scaled' is not defined